name: Daily Commit

on:
  schedule:
    - cron: '15 5 * * *'  # Runs daily at 05:15 UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write  # ✅ Allow push access to GitHub token

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Commit and push 22f3000812@ds.study.iitm.ac.in
        run: |
          echo "Run at $(date -u)" >> daily-log.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Daily commit from GitHub Action" || echo "No changes to commit"
          git push
