name: Daily Commit

on:
  schedule:
    - cron: '12 5 * * *'  # Runs daily at 05:12 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit 22f3000812@ds.study.iitm.ac.in
        run: |
          echo "Commit run at $(date)" >> daily-log.txt
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Daily commit from GitHub Action"
          git push
